### ISSUE TITLE
About setting on CIFAR100

### ISSUE THREAD

**Issue by eddielyc** [chrysts/geodesic_continual_learning#1]
Thank you so much for this excellent work!

Recently, I try to reproduce your results on CIFAR100. However, it seems that this repo only provides the scripts for ImageNet100. I will appreciate it so much if the scripts or code for CIFAR100 could be uploaded for quick reproduction.

And another question, as mentioned in the paper, when setting the number of dimensions in subspace `n=127`, the model performs best. However, as far as I know, the modified ResNet32 outputs 64 dims features for CIFAR images, which span space with lower dimensions than subspace. I'm wondering if there's something wrong with my comprehension.

Thank you so much for your time and consideration, and best wishes!

**Comment by chrysts** [comment]
Hi eddielyc,

Thank you for your interest to our work.
Unfortunately, I do not plan to release it very soon.
If it is urgent for you, I can suggest the following:

You can grab the core algorithm:
check: https://github.com/chrysts/geodesic_continual_learning/blob/main/utils_incremental/incremental_train_and_eval_LF.py

, and apply it to the existing codebase (having CIFAR-100):
https://github.com/yaoyao-liu/class-incremental-learning

**Comment by eddielyc** [comment]
I apologize for my delay. 

Thank you for your response and I will try it later.
