### ISSUE TITLE
Error while running geodesic_continual_learning code

### ISSUE THREAD

**Issue by PramodJNUSCS** [chrysts/geodesic_continual_learning#2]
Hello Sir,
              When I am trying to run the code geodesic_continual_learning, I am getting the error at different places. Please check it and help me so that i can run this code.

![Screenshot (159)](https://user-images.githubusercontent.com/53903377/140962302-8dbb622a-587f-4355-b6ba-57c4a5ad0023.png)

**Comment by chrysts** [comment]
Hi PramodJNUSCS,

Thanks for your interest to our work.
You might need to check your python settings and command on windows.
I am not quite handy in running python on windows. You might seek some answers on stackoverflow.

Cheers
